-- CreateTable
CREATE TABLE "Lead" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "email" TEXT,
    "linkedinUrl" TEXT,
    "linkedinProfile" TEXT,
    "currentCompany" TEXT,
    "role" TEXT,
    "replied" BOOLEAN NOT NULL DEFAULT false,
    "repliedAt" DATETIME,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "Lead_email_key" ON "Lead"("email");

-- CreateIndex
CREATE INDEX "Lead_createdAt_idx" ON "Lead"("createdAt");

-- CreateIndex
CREATE INDEX "Lead_replied_idx" ON "Lead"("replied");

-- AlterTable: add leadId FK to ReachOut. Using ALTER TABLE ADD COLUMN
-- (rather than the table-redefine pattern Prisma normally emits) so the
-- migration can run without holding an exclusive lock on the whole DB —
-- a hot dev server keeps the DB busy enough to deadlock that pattern.
ALTER TABLE "ReachOut" ADD COLUMN "leadId" TEXT REFERENCES "Lead" ("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- CreateIndex
CREATE INDEX "ReachOut_leadId_idx" ON "ReachOut"("leadId");

-- Backfill: collapse existing ReachOut rows into one Lead per distinct
-- recipientEmail. We reuse the most recent ReachOut.id of each email
-- group as the Lead.id so it sits in the same id namespace as everything
-- else generated by `secrets.token_urlsafe(12)`. Then point every
-- ReachOut at its matching Lead via the unique email.
INSERT INTO "Lead" ("id", "name", "email", "linkedinProfile", "createdAt", "updatedAt")
SELECT
    r."id",
    r."recipientName",
    r."recipientEmail",
    CASE
        WHEN r."linkedinProfile" IS NOT NULL AND length(trim(r."linkedinProfile")) > 0
        THEN r."linkedinProfile"
        ELSE NULL
    END,
    r."createdAt",
    r."updatedAt"
FROM "ReachOut" r
WHERE r."recipientEmail" IS NOT NULL
    AND length(trim(r."recipientEmail")) > 0
    AND r."id" = (
        SELECT r2."id"
        FROM "ReachOut" r2
        WHERE r2."recipientEmail" = r."recipientEmail"
        ORDER BY r2."createdAt" DESC, r2."id" DESC
        LIMIT 1
    );

UPDATE "ReachOut"
SET "leadId" = (
    SELECT l."id"
    FROM "Lead" l
    WHERE l."email" = "ReachOut"."recipientEmail"
)
WHERE "recipientEmail" IS NOT NULL
    AND length(trim("recipientEmail")) > 0;
